"""init tables

Revision ID: 3f9b560d22a5
Revises: 
Create Date: 2026-03-17 13:13:59.244489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f9b560d22a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('title_slug', sa.String(length=200), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('ac_rate', sa.Float(), nullable=False),
    sa.Column('core_skills', sa.JSON(), nullable=True),
    sa.Column('suitable_level', sa.String(length=20), nullable=True),
    sa.Column('thinking_pattern', sa.String(length=200), nullable=True),
    sa.Column('semantic_text', sa.Text(), nullable=True),
    sa.Column('is_indexed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title_slug')
    )
    op.create_table('recommendation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('recommend_type', sa.String(length=20), nullable=False),
    sa.Column('user_level', sa.Float(), nullable=True),
    sa.Column('was_clicked', sa.Boolean(), nullable=False),
    sa.Column('was_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('calibration_done', sa.Boolean(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('solved_ids', sa.JSON(), nullable=False),
    sa.Column('failed_ids', sa.JSON(), nullable=False),
    sa.Column('swap_date', sa.String(length=10), nullable=True),
    sa.Column('swap_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('interview_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('time_used', sa.Integer(), nullable=True),
    sa.Column('time_limit', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('submit_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('select_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_sessions')
    op.drop_table('user_profiles')
    op.drop_table('recommendation_logs')
    op.drop_table('questions')
    # ### end Alembic commands ###
