"""add test_case table

Revision ID: f5172faa2f8a
Revises: 90e1d7bdf67c
Create Date: 2026-03-18 11:16:02.398869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5172faa2f8a'
down_revision: Union[str, None] = '90e1d7bdf67c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.Column('case_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('question_test_cases')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_test_cases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('input_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expected', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('case_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='question_test_cases_question_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='question_test_cases_pkey')
    )
    op.drop_table('test_cases')
    # ### end Alembic commands ###
